sudo: required

language: node_js

services:
  - docker

before_install:
  - docker build -t alpine-node-onbuild .
  - docker build -t alpine-node-onbuild-test tests/
  - docker run -d -p 127.0.0.1:3000:3000 alpine-node-onbuild-test
  - docker ps -a

script:
  - curl 127.0.0.1:3000 | grep "Hello World!"
