sudo: required

language: javascript

secure: "GDeAkH6A0ItW6fP7UoyifwH+Wi/re8JsK6wP8ElplvMqOGiCZBLEMXogz4gcE9tONLvTbv4L4MuxEl64+HMa9RpRPr5+n40ys7SADxlMCv8uaJowYgugLiZOJ03bJkXJ+XC2x7kQ+XuE1USAz8YIF8kxcDf0Zdy9GoG+M7iUTv8DAqOkoWeqiZSYOeTv6MJsis8ENZxQ3I9i3Nhv498AWUdbObaIao9Cf8aW2qlSVmJopW6GLB/WGf9HA9DxlE6MQ4lrvu8dfDG+bvUyftdt09UsCyFo8wgZ01P5AvXH2HOabz8z48ohvgSek8dqK4yFlMDIHuQFz3avUtN+/oTOD3nWS0DsCLQxub+4L24IvWoayW16bFTs6LgreiCOzh6UHv4u5CUtCq9TYee4cdvmkaDopz9cPTbYyU4qTkhOim2M2alN7iQ1vgghUWY/RITUCsTg8wFn+axtFswahOiowoMvBDLSbltohKADYQPB7Gn3nz4Jy7ozj0HiPPMI+rstQoh1mp5XQXvh+Xsq7IVviPAFfaEWDNC9RO6habYe7mrpG+k6HE/iv5ylH0rqoe057iJ3b4i48uqJFZWCH/b0Tbg89tBGhi4C0IXnbhT6PFk6+3Caa/eUJjG029V3AZ12wENqBdrIYjIMPNR7yThc8pmeWd9lRZF6w/+3f6mzlZ0="

services:
  - docker

before_install:
  - docker build -t iadknet/alpine-node-onbuild .
  - docker build -t iadknet/alpine-node-onbuild-test tests/
  - docker run -d -p 127.0.0.1:3000:3000 iadknet/alpine-node-onbuild-tests"
  - docker ps -a

script:
  - curl 127.0.0.1:3000 | grep "Hello World!"
